[package]
name = "zephyr"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8.6", features = ["multipart", "json"] }
tokio = { version = "1", features = ["full"] }
serde_json = "1.0"